Adding trigger_http input
terraform-google-modules/terraform-google-event-function pull request #56
Opened 2020-11-17 00:07 UTC by jtyr

This PR is adding an extra input called `trigger_http` which allows to create a function which is triggered by any HTTP request. This makes the previously required input `event_trigger` optional as only one of them can be used at a time.

2020-11-17 00:45 UTC, bharathkkb requested changes
Thanks for the PR! We may need to set it `trigger_http` to `null` as CI given an error which I suspect is due to `trigger_http = false` and `event_trigger` block being present.
```
       module.automatic_labelling_from_localhost.module.event_project_log_entry.google_pubsub_topic_iam_member.main: Creating...
       module.automatic_labelling_from_localhost.module.event_project_log_entry.google_pubsub_topic_iam_member.main: Creation complete after 4s [id=projects/ci-event-function-9402/topics/infinite-alpaca/roles/pubsub.publisher/serviceaccount:p771980061706-101280@gcp-sa-logging.iam.gserviceaccount.com]
       
       Error: ConflictsWith
       
         on ../../../main.tf line 70, in resource "google_cloudfunctions_function" "main":
         70: resource "google_cloudfunctions_function" "main" {
       
       "event_trigger": conflicts with trigger_http
       
```

2020-11-17 00:45 UTC, bharathkkb commented on variables.tf
> +  default     = false
```suggestion
  default     = null
```

2020-11-17 00:45 UTC, bharathkkb commented on outputs.tf
> +  value       = var.trigger_http ? google_cloudfunctions_function.main.https_trigger_url : ""
```suggestion
  value       = var.trigger_http != null ? google_cloudfunctions_function.main.https_trigger_url : ""
```

2020-11-17 00:45 UTC, bharathkkb commented on main.tf
> +    for_each = var.trigger_http ? [] : [1]
```suggestion
    for_each = var.trigger_http != null ? [] : [1]
```

2020-11-25 23:55 UTC, jtyr commented
Sorry for the delay. I have modify the code as you requested. Please review it and let me know if there is something else needed.

2021-01-15 15:05 UTC, jtyr commented
@bharathkkb please could you review this?

2021-03-19 18:26 UTC, bharathkkb commented
/gcbrun

2021-03-20 10:01 UTC, jtyr commented
@bharathkkb Please review the PR.

2021-03-20 19:37 UTC, bharathkkb approved these changes

2021-03-20 19:38 UTC, bharathkkb commented
Thanks @jtyr and apologies for missing this earlier

2021-03-20 19:38 UTC, merged